extends: airbnb
rules:
  semi: ["error", "never"]
  comma-dangle: ["error", "never"]
  import/no-extraneous-dependencies: ["off"]
  react/jsx-filename-extension: ["error", {
    "extensions": [
      ".js",
      ".jsx"
    ]
  }]
  object-curly-newline: ["off"]
  react/forbid-prop-types: ["error", {
    "forbid": [
      "any",
      "array"
    ]
  }]
  import/no-unresolved: ["off"]
